name: robot_router

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    path_provider: ^2.0.8
    json_annotation: ^4.4.0

dev_dependencies:
    flutter_lints: ^1.0.0
    flutter_app_name: ^0.1.0
    json_serializable: ^6.1.1
    build_runner: ^2.1.5

flutter_app_name:
  name: "Robot Router"

flutter:
    uses-material-design: true